//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectumDSExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectumDSExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;DevelopmentStudioProperties&gt;
        ///  &lt;AppServerType value=&quot;WebApi&quot; /&gt;
        ///  &lt;AskCredentialsOnClientRun value=&quot;False&quot; /&gt;
        ///  &lt;AskCredentialsOnClientRun_Local value=&quot;False&quot; /&gt;
        ///  &lt;CodeAnalysis.FxCopPath value=&quot;&quot; /&gt;
        ///  &lt;Properties name=&quot;CodeCompletionOptions&quot;&gt;
        ///    &lt;CompleteWhenTyping value=&quot;False&quot; /&gt;
        ///    &lt;DataUsageCacheEnabled value=&quot;True&quot; /&gt;
        ///    &lt;DataUsageCacheItemCount value=&quot;500&quot; /&gt;
        ///    &lt;EnableCC value=&quot;True&quot; /&gt;
        ///    &lt;InsightEnabled value=&quot;True&quot; /&gt;
        ///    &lt;InsightRefreshOnComma value=&quot;True&quot; /&gt;
        ///    &lt;KeywordComple [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string blackBody {
            get {
                return ResourceManager.GetString("blackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brightness {
            get {
                object obj = ResourceManager.GetObject("brightness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap changeColor {
            get {
                object obj = ResourceManager.GetObject("changeColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;SerializedValue name=&quot;CustomizedHighlightingRules&quot;&gt;   
        ///  &lt;ArrayOfCustomizedHighlightingColor xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;/ArrayOfCustomizedHighlightingColor&gt;
        /// &lt;/SerializedValue&gt;.
        /// </summary>
        internal static string colorsContainer {
            get {
                return ResourceManager.GetString("colorsContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap compactSize {
            get {
                object obj = ResourceManager.GetObject("compactSize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deleteButton {
            get {
                object obj = ResourceManager.GetObject("deleteButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;DevelopmentStudioProperties&gt;
        ///  &lt;AppServerType value=&quot;WebApi&quot; /&gt;
        ///  &lt;AskCredentialsOnClientRun value=&quot;False&quot; /&gt;
        ///  &lt;AskCredentialsOnClientRun_Local value=&quot;False&quot; /&gt;
        ///  &lt;CodeAnalysis.FxCopPath value=&quot;&quot; /&gt;
        ///  &lt;Properties name=&quot;CodeCompletionOptions&quot;&gt;
        ///    &lt;CompleteWhenTyping value=&quot;False&quot; /&gt;
        ///    &lt;DataUsageCacheEnabled value=&quot;True&quot; /&gt;
        ///    &lt;DataUsageCacheItemCount value=&quot;500&quot; /&gt;
        ///    &lt;EnableCC value=&quot;True&quot; /&gt;
        ///    &lt;InsightEnabled value=&quot;True&quot; /&gt;
        ///    &lt;InsightRefreshOnComma value=&quot;True&quot; /&gt;
        ///    &lt;KeywordComple [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string DevelopmentStudioProperties_black {
            get {
                return ResourceManager.GetString("DevelopmentStudioProperties_black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;DevelopmentStudioProperties&gt;
        ///  &lt;CodeAnalysis.FxCopPath value=&quot;&quot; /&gt;
        ///  &lt;Properties name=&quot;CodeCompletionOptions&quot;&gt;
        ///    &lt;EnableCC value=&quot;True&quot; /&gt;
        ///    &lt;TooltipsEnabled value=&quot;True&quot; /&gt;
        ///    &lt;TooltipsOnlyWhenDebugging value=&quot;False&quot; /&gt;
        ///  &lt;/Properties&gt;
        ///  &lt;SerializedValue name=&quot;CodeEditorOptions&quot;&gt;
        ///    &lt;CodeEditorOptions xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///      &lt;AllowScrollBelowDocument&gt;true&lt;/AllowScrollBelowDocument&gt;
        ///      &lt;FontFamily&gt;Consolas&lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string DevelopmentStudioProperties_white {
            get {
                return ResourceManager.GetString("DevelopmentStudioProperties_white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;DevelopmentStudioProperties&gt;
        ///  &lt;AppServerType value=&quot;WebApi&quot; /&gt;
        ///  &lt;AskCredentialsOnClientRun value=&quot;False&quot; /&gt;
        ///  &lt;AskCredentialsOnClientRun_Local value=&quot;False&quot; /&gt;
        ///  &lt;CodeAnalysis.FxCopPath value=&quot;&quot; /&gt;
        ///  &lt;Properties name=&quot;CodeCompletionOptions&quot;&gt;
        ///    &lt;CompleteWhenTyping value=&quot;False&quot; /&gt;
        ///    &lt;DataUsageCacheEnabled value=&quot;True&quot; /&gt;
        ///    &lt;DataUsageCacheItemCount value=&quot;500&quot; /&gt;
        ///    &lt;EnableCC value=&quot;True&quot; /&gt;
        ///    &lt;InsightEnabled value=&quot;True&quot; /&gt;
        ///    &lt;InsightRefreshOnComma value=&quot;True&quot; /&gt;
        ///    &lt;KeywordComple [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string firstSettings {
            get {
                return ResourceManager.GetString("firstSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fullSize {
            get {
                object obj = ResourceManager.GetObject("fullSize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  &lt;SerializedValue name=&quot;DebuggingOptions&quot;&gt;
        ///    &lt;DebuggingOptions xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///      &lt;EnableJustMyCode&gt;true&lt;/EnableJustMyCode&gt;
        ///      &lt;StepOverNoSymbols&gt;true&lt;/StepOverNoSymbols&gt;
        ///      &lt;StepOverAutoGeneratedCode&gt;true&lt;/StepOverAutoGeneratedCode&gt;
        ///      &lt;StepOverDebuggerAttributes&gt;true&lt;/StepOverDebuggerAttributes&gt;
        ///      &lt;StepOverAllProperties&gt;false&lt;/StepOverAllProperties&gt;
        ///      &lt;StepOverSingleLineProperties&gt;false&lt;/StepOv [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string lastSettings {
            get {
                return ResourceManager.GetString("lastSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoDirectum {
            get {
                object obj = ResourceManager.GetObject("logoDirectum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap parameters {
            get {
                object obj = ResourceManager.GetObject("parameters", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap propertieCod {
            get {
                object obj = ResourceManager.GetObject("propertieCod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save3d {
            get {
                object obj = ResourceManager.GetObject("save3d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap savedChanges {
            get {
                object obj = ResourceManager.GetObject("savedChanges", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThemeButton {
            get {
                object obj = ResourceManager.GetObject("ThemeButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap themeIco {
            get {
                object obj = ResourceManager.GetObject("themeIco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;DevelopmentStudioProperties&gt;
        ///  &lt;AppServerType value=&quot;WebApi&quot; /&gt;
        ///  &lt;AskCredentialsOnClientRun value=&quot;False&quot; /&gt;
        ///  &lt;AskCredentialsOnClientRun_Local value=&quot;False&quot; /&gt;
        ///  &lt;CodeAnalysis.FxCopPath value=&quot;&quot; /&gt;
        ///  &lt;Properties name=&quot;CodeCompletionOptions&quot;&gt;
        ///    &lt;CompleteWhenTyping value=&quot;False&quot; /&gt;
        ///    &lt;DataUsageCacheEnabled value=&quot;True&quot; /&gt;
        ///    &lt;DataUsageCacheItemCount value=&quot;500&quot; /&gt;
        ///    &lt;EnableCC value=&quot;True&quot; /&gt;
        ///    &lt;InsightEnabled value=&quot;True&quot; /&gt;
        ///    &lt;InsightRefreshOnComma value=&quot;True&quot; /&gt;
        ///    &lt;KeywordComple [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string whiteBody {
            get {
                return ResourceManager.GetString("whiteBody", resourceCulture);
            }
        }
    }
}
